name: Chocolatine Workflow

on: [push, pull_request]

env:
  MIRROR_URL: git@github.com:EpitechPGEPromo2029/B-DOP-200-LYN-2-1-chocolatine-iuliia.dabizha.git

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ env.MIRROR_URL }}
          token: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
      - name: Check Coding Style
        run: |
          check.sh $(pwd) $(pwd) > coding-style-reports.log
          [ -s coding-style-reports.log ] || exit 0

  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Compilation
        run: |
          timeout 2m make
          make clean
          [ -x "chocolatine_mirror" ] || exit 1

#   run_tests:
#     runs-on: ubuntu-latest
#     container:
#       image: epitechcontent/epitest-docker
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Run Tests
#         run: timeout 2m make tests_run

  push_to_mirror:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GIT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - name: Mirror Push
        run: |
          git remote add mirror ${{ env.MIRROR_URL }}
          git push --mirror mirror
